export class DoctorOnboarding {
  constructor(
    public username: string,
    public gender: string,
    public phone: string,
    public registrationNumber: string,
    public country: string,
    public state: string,
    public experience: string,
    public bio: string,
    public specializations: string[],
    public consultationModes: string[],
    public consultationFee: string,
    public languages: string[],
    public consultationDuration: string,
    public preferredMode: string,
    public acceptingPatients: boolean = true,
    public profileVisibility: boolean = true,
    public id: string,
  ) {}

  static create(
    username: string,
    gender: string,
    phone: string,
    registrationNumber: string,
    country: string,
    state: string,
    experience: string,
    bio: string,
    specializations: string[],
    consultationModes: string[],
    consultationFee: string,
    languages: string[],
    consultationDuration: string,
    preferredMode: string,
    acceptingPatients: boolean = true,
    profileVisibility: boolean = true,
    id: string,
  ): DoctorOnboarding {
    return new DoctorOnboarding(
      username,
      gender,
      phone,
      registrationNumber,
      country,
      state,
      experience,
      bio,
      specializations,
      consultationModes,
      consultationFee,
      languages,
      consultationDuration,
      preferredMode,
      acceptingPatients,
      profileVisibility,
      id,
    );
  }
}
